import Link from 'next/link';
import Card from '@/components/ui/Card';
import Button from '@/components/ui/Button';

export default function DemoPage() {
  return (
    <div className="space-y-8">
      <div className="text-center mb-12">
        <h1 className="text-3xl font-bold text-gray-900">Interactive Demo</h1>
        <p className="mt-2 text-lg text-gray-600">
          Explore the capabilities of our Educational Content Generator API
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Questions Card */}
        <Card title="Questions" className="h-full">
          <div className="space-y-4">
            <p className="text-gray-600">
              Generate, view, and evaluate educational questions for various subjects and difficulty levels.
            </p>
            <div className="space-y-2">
              <Link href="/demo/questions/view" className="block">
                <Button variant="outline" fullWidth>
                  View Questions
                </Button>
              </Link>
              <Link href="/demo/questions/generate" className="block">
                <Button variant="outline" fullWidth>
                  Generate Questions
                </Button>
              </Link>
              <Link href="/demo/questions/grade" className="block">
                <Button variant="outline" fullWidth>
                  Grade Questions
                </Button>
              </Link>
              <Link href="/demo/questions/tag" className="block">
                <Button variant="outline" fullWidth>
                  Tag Questions
                </Button>
              </Link>
            </div>
          </div>
        </Card>
        
        {/* Articles Card */}
        <Card title="Articles" className="h-full">
          <div className="space-y-4">
            <p className="text-gray-600">
              Generate, view, and evaluate educational articles for various subjects and age groups.
            </p>
            <div className="space-y-2">
              <Link href="/demo/articles/view" className="block">
                <Button variant="outline" fullWidth>
                  View Articles
                </Button>
              </Link>
              <Link href="/demo/articles/generate" className="block">
                <Button variant="outline" fullWidth>
                  Generate Articles
                </Button>
              </Link>
              <Link href="/demo/articles/grade" className="block">
                <Button variant="outline" fullWidth>
                  Grade Articles
                </Button>
              </Link>
              <Link href="/demo/articles/tag" className="block">
                <Button variant="outline" fullWidth>
                  Tag Articles
                </Button>
              </Link>
            </div>
          </div>
        </Card>
      </div>

      <div className="mt-12 bg-blue-50 p-6 rounded-lg border border-blue-100">
        <h2 className="text-xl font-semibold text-blue-800 mb-2">Quick Start</h2>
        <p className="text-blue-700 mb-4">
          Try out the &quot;View Questions&quot; or &quot;View Articles&quot; section to see example content generated by our API.
        </p>
        <div className="flex space-x-4">
          <Link href="/demo/questions/view">
            <Button variant="primary">
              View Questions
            </Button>
          </Link>
          <Link href="/demo/articles/view">
            <Button variant="primary">
              View Articles
            </Button>
          </Link>
        </div>
      </div>
    </div>
  );
} 